name: SFDX Test Run on Push

on: [push]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
