name: SFDX Test Run on Push

on: [push]

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: ./
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: sfdx-test-run
        run: sfdx force:apex:test:run -l RunLocalTests -w 30
